export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const GET_DEPS = 'GET_DEPS';
export const GET_DEPS_SUCCESS = 'GET_DEPS_SUCCESS';
export const GET_DEPS_FAILED = 'GET_DEPS_FAILED';

export const GET_PLACES = 'GET_PLACES';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILED = 'GET_PLACES_FAILED';

export const ADD_PLACE = 'ADD_PLACE';
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS';
export const ADD_PLACE_FAILED = 'ADD_PLACE_FAILED';

export const RESERVE = 'RESERVE';
export const RESERVE_SUCCESS = 'RESERVE_SUCCESS';
export const RESERVE_FAILED = 'RESERVE_FAILED';

export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';
export const GET_RESERVATIONS_FAILED = 'GET_RESERVATIONS_FAILED';

export const REPORT_PLACE = 'REPORT_PLACE';
export const REPORT_PLACE_SUCCESS = 'REPORT_PLACE_SUCCESS';
export const REPORT_PLACE_FAILED = 'REPORT_PLACE_REPORT';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED';

export const GET_PLACE_REVIEWS = 'GET_PLACE_REVIEWS';
export const GET_PLACE_REVIEWS_SUCCESS = 'GET_PLACE_REVIEWS_SUCCESS';
export const GET_PLACE_REVIEWS_FAILED = 'GET_PLACE_REVIEWS_FAILED';

export const ADD_VOUCHER = 'ADD_VOUCHER';
export const ADD_VOUCHER_SUCCESS = 'ADD_VOUCHER_SUCCESS';
export const ADD_VOUCHER_FAILED = 'ADD_VOUCHER_FAILED';

export const SEND_CONTACT = 'SEND_CONTACT';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAILED = 'SEND_CONTACT_FAILED';

export const GET_ABOUT = 'GET_ABOUT';
export const GET_ABOUT_SUCCESS = 'GET_ABOUT_SUCCESS';
export const GET_ABOUT_FAILED = 'GET_ABOUT_FAILED';

export const GET_TERMS = 'GET_TERMS';
export const GET_TERMS_SUCCESS = 'GET_TERMS_SUCCESS';
export const GET_TERMS_FAILED = 'GET_TERMS_FAILED';

export const NEW_CONVERSATION = 'NEW_CONVERSATION';
export const NEW_CONVERSATION_SUCCESS = 'NEW_CONVERSATION_SUCCESS';
export const NEW_CONVERSATION_FAILED = 'NEW_CONVERSATION_FAILED';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';

export const LIKE_PLACE = 'LIKE_PLACE';
export const LIKE_PLACE_SUCCESS = 'LIKE_PLACE_SUCCESS';
export const LIKED_PLACE_FAILED = 'LIKE_PLACE_FAILED';